# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\gercek_makine.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(492, 512)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 471, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 170, 471, 321))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.carpma = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.carpma.setFont(font)
        self.carpma.setObjectName("carpma")
        self.gridLayout.addWidget(self.carpma, 1, 3, 1, 1)
        self.esittir = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.esittir.setFont(font)
        self.esittir.setObjectName("esittir")
        self.gridLayout.addWidget(self.esittir, 4, 2, 1, 1)
        self.bolme = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.bolme.setFont(font)
        self.bolme.setObjectName("bolme")
        self.gridLayout.addWidget(self.bolme, 2, 3, 1, 1)
        self.karekok = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.karekok.setFont(font)
        self.karekok.setObjectName("karekok")
        self.gridLayout.addWidget(self.karekok, 3, 3, 1, 1)
        self.ussunualma = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.ussunualma.setFont(font)
        self.ussunualma.setObjectName("ussunualma")
        self.gridLayout.addWidget(self.ussunualma, 4, 3, 1, 1)
        self.bes = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.bes.setFont(font)
        self.bes.setObjectName("bes")
        self.gridLayout.addWidget(self.bes, 2, 1, 1, 1)
        self.iki = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.iki.setFont(font)
        self.iki.setObjectName("iki")
        self.gridLayout.addWidget(self.iki, 3, 1, 1, 1)
        self.bir = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.bir.setFont(font)
        self.bir.setObjectName("bir")
        self.gridLayout.addWidget(self.bir, 3, 0, 1, 1)
        self.uc = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.uc.setFont(font)
        self.uc.setObjectName("uc")
        self.gridLayout.addWidget(self.uc, 3, 2, 1, 1)
        self.sifir = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.sifir.setFont(font)
        self.sifir.setObjectName("sifir")
        self.gridLayout.addWidget(self.sifir, 4, 1, 1, 1)
        self.alti = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.alti.setFont(font)
        self.alti.setObjectName("alti")
        self.gridLayout.addWidget(self.alti, 2, 2, 1, 1)
        self.ciftsifir = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.ciftsifir.setFont(font)
        self.ciftsifir.setObjectName("ciftsifir")
        self.gridLayout.addWidget(self.ciftsifir, 4, 0, 1, 1)
        self.yedi = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.yedi.setFont(font)
        self.yedi.setObjectName("yedi")
        self.gridLayout.addWidget(self.yedi, 1, 0, 1, 1)
        self.sekiz = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.sekiz.setFont(font)
        self.sekiz.setObjectName("sekiz")
        self.gridLayout.addWidget(self.sekiz, 1, 1, 1, 1)
        self.dort = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.dort.setFont(font)
        self.dort.setObjectName("dort")
        self.gridLayout.addWidget(self.dort, 2, 0, 1, 1)
        self.dokuz = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.dokuz.setFont(font)
        self.dokuz.setObjectName("dokuz")
        self.gridLayout.addWidget(self.dokuz, 1, 2, 1, 1)
        self.temizleme = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.temizleme.setFont(font)
        self.temizleme.setObjectName("temizleme")
        self.gridLayout.addWidget(self.temizleme, 0, 0, 1, 1)
        self.toplama = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.toplama.setFont(font)
        self.toplama.setObjectName("toplama")
        self.gridLayout.addWidget(self.toplama, 0, 1, 1, 1)
        self.cikarma = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.cikarma.setFont(font)
        self.cikarma.setObjectName("cikarma")
        self.gridLayout.addWidget(self.cikarma, 0, 2, 1, 1)
        self.karesinialma = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.karesinialma.setFont(font)
        self.karesinialma.setObjectName("karesinialma")
        self.gridLayout.addWidget(self.karesinialma, 0, 3, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.carpma.setText(_translate("Form", "X"))
        self.esittir.setText(_translate("Form", "="))
        self.bolme.setText(_translate("Form", "/"))
        self.karekok.setText(_translate("Form", "√"))
        self.ussunualma.setText(_translate("Form", "x**"))
        self.bes.setText(_translate("Form", "5"))
        self.iki.setText(_translate("Form", "2"))
        self.bir.setText(_translate("Form", "1"))
        self.uc.setText(_translate("Form", "3"))
        self.sifir.setText(_translate("Form", "0"))
        self.alti.setText(_translate("Form", "6"))
        self.ciftsifir.setText(_translate("Form", "00"))
        self.yedi.setText(_translate("Form", "7"))
        self.sekiz.setText(_translate("Form", "8"))
        self.dort.setText(_translate("Form", "4"))
        self.dokuz.setText(_translate("Form", "9"))
        self.temizleme.setText(_translate("Form", "C"))
        self.toplama.setText(_translate("Form", "+"))
        self.cikarma.setText(_translate("Form", "-"))
        self.karesinialma.setText(_translate("Form", "x²"))

        self.ciftsifir.clicked.connect(self.ciftsifirtiklama)
        self.sifir.clicked.connect(self.sifirtiklama)
        self.bir.clicked.connect(self.birtiklama)
        self.iki.clicked.connect(self.ikitiklama)
        self.uc.clicked.connect(self.uctiklama)
        self.dort.clicked.connect(self.dorttiklama)
        self.bes.clicked.connect(self.bestiklama)
        self.alti.clicked.connect(self.altitiklama)
        self.yedi.clicked.connect(self.yeditiklama)
        self.sekiz.clicked.connect(self.sekiztiklama)
        self.dokuz.clicked.connect(self.dokuztiklama)
        self.esittir.clicked.connect(self.esittirtiklama)
        self.toplama.clicked.connect(self.toplamatiklama)
        self.temizleme.clicked.connect(self.temizlemetiklama)
        self.cikarma.clicked.connect(self.cikarmatiklama)
        self.bolme.clicked.connect(self.bolmetiklama)
        self.carpma.clicked.connect(self.carpmatiklama)
        self.karesinialma.clicked.connect(self.karesinialmatiklama)
        self.karekok.clicked.connect(self.karekoktiklama)
        self.ussunualma.clicked.connect(self.ussunualmatiklama)

    def ciftsifirtiklama(self):
        suan = self.lineEdit.text()
        self.lineEdit.setText(suan + "00")

    def birtiklama(self):
        suan = self.lineEdit.text()
        self.lineEdit.setText(suan + "1")

    def ikitiklama(self):
        suan = self.lineEdit.text()
        self.lineEdit.setText(suan + "2")
    def sifirtiklama(self):
        suan = self.lineEdit.text()
        self.lineEdit.setText(suan + "0")
    def uctiklama(self):
        suan = self.lineEdit.text()
        self.lineEdit.setText(suan + "3")

    def dorttiklama(self):
        suan = self.lineEdit.text()
        self.lineEdit.setText(suan + "4")
    def bestiklama(self):
        suan = self.lineEdit.text()
        self.lineEdit.setText(suan + "5")

    def altitiklama(self):
        suan = self.lineEdit.text()
        self.lineEdit.setText(suan + "6")

    def yeditiklama(self):
        suan = self.lineEdit.text()
        self.lineEdit.setText(suan + "7")
    def sekiztiklama(self):
        suan = self.lineEdit.text()
        self.lineEdit.setText(suan + "8")
    def dokuztiklama(self):
        suan = self.lineEdit.text()
        self.lineEdit.setText(suan + "9")

    def toplamatiklama(self):
        suan = self.lineEdit.text()
        self.lineEdit.setText(suan + "+")


    def esittirtiklama(self):

        metin = self.lineEdit.text()
        (data) = eval(metin)


        self.lineEdit.setText(str(data))
    def temizlemetiklama(self):
        self.lineEdit.clear()

    def cikarmatiklama(self):
        suan = self.lineEdit.text()
        self.lineEdit.setText(suan + "-")
    def bolmetiklama(self):
        suan = self.lineEdit.text()
        self.lineEdit.setText(suan + "/")

    def carpmatiklama(self):
        suan = self.lineEdit.text()
        self.lineEdit.setText(suan + "*")

    def karesinialmatiklama(self):
        suan = self.lineEdit.text()
        data = eval(suan)**2
        self.lineEdit.setText(str(data))

    def karekoktiklama(self):
        import math
        suan = self.lineEdit.text()
        data = math.sqrt(eval(suan))
        self.lineEdit.setText(str(data))

    def ussunualmatiklama(self):
        suan = self.lineEdit.text()

    def ussunualmatiklama(self):
        suan = self.lineEdit.text()
        self.lineEdit.setText(suan + "**")

















if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
